//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TodoListDBEntities : DbContext
    {
        public TodoListDBEntities()
            : base("name=TodoListDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Work> Works { get; set; }
        public virtual DbSet<Work_Employee> Work_Employee { get; set; }
        public virtual DbSet<WorkList> WorkLists { get; set; }
        public virtual DbSet<WorkList_Employee> WorkList_Employee { get; set; }
        public virtual DbSet<WorkListStatu> WorkListStatus { get; set; }
        public virtual DbSet<WorkStatu> WorkStatus { get; set; }
    }
}
